### ISSUE TITLE
Add/Remove effect doesn't work on 1.8.8

### ISSUE THREAD

**Issue by Nukecraft5419** [Syrent/VelocityVanish#113]
### Server backend version

FlamePaper 1.8.8

### Server Velocity version

Velocity build 229

### VelocityVanish version

3.18.0

### Describe the bug

https://media.essential.gg/4a90c3e5-54f3-4c31-7580-22f33cced000
https://i.imgur.com/vVlRjST.png

### Expected behavior

The plugin works but gives errors in both console and chat while on other servers it does not

### Steps to reproduce

I just installed the plugin

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Send full server log

**Comment by Nukecraft5419** [comment]
[2023-02-22-4.log](https://github.com/Syrent/VelocityVanish/files/10819137/2023-02-22-4.log)

**Comment by Syrent** [comment]
Try this version:
https://cdn.discordapp.com/attachments/854786458186940446/1078703515339341834/VelocityVanish_v3.18.0.jar
Let me know if it works

**Comment by Nukecraft5419** [comment]
If it's possible I don't know if you have Discord seno we can also talk through Session my Session ID is 051443b8954345eb230a4741aede9520b2b1dae9f17043fd74cd9f5cbb25edce32 and everything is anonymous Session is a messaging app that you don't have to give any data like email, phone number, etc. it doesn't even collect meta data so it's great and kind of disposable or permanent depending on when you want to keep your Session ID active I use it to get in touch as an alternative to Discord just for the messaging part

**Comment by Syrent** [comment]
We can talk in this discord: https://discord.gg/RD4NgvCd
