### ISSUE TITLE
Vanish On-Join Bug

### ISSUE THREAD

**Issue by DeOpping** [Syrent/VelocityVanish#116]
### Server backend version

Purpur 1.19.3 (git-Purpur-1920)

### Server Velocity version

velocity-3.2.0-SNAPSHOT-229

### VelocityVanish version

3.18.0

### Describe the bug

When an opped player joins the server, they are automatically put into Vanish.

However, it does not count towards the placeholders (such as %velocityvanish_online_total%).
Furthermore, when the user does /vanish, it says they have successfully vanished, as if they weren't already (however players cannot actually see them beforehand, nor do they appear on the tablist).

### Expected behavior

When an opped player joins (or user with the vanish on join permission) it should automatically vanish them, count towards any placeholders, and when they type /vanish it should un-vanish them.

### Steps to reproduce

1. Install the plugin like normal.
2. If you are not opped, op yourself, relog. Otherwise, just join.
3. Parse the VelocityVanish online placeholders, type /vanish.

### Additional info

Backend Server Log: https://paste.md-5.net/lodahahixe.md
Proxy Log: https://paste.md-5.net/vesocacopo.md

1. Joined the server:
![VV - First Joined](https://user-images.githubusercontent.com/79672154/221373479-87be455f-606e-4381-9126-0475daef2e04.png)

2. First typed /vanish:
![VV - Vanished First Time](https://user-images.githubusercontent.com/79672154/221373493-0016526f-8b3e-4355-8881-ab7373ba4169.png)

The chat:
![VV - Vanished First Time Chat](https://user-images.githubusercontent.com/79672154/221373505-91e7d4dd-0ad8-48ef-a4de-f1130e18b790.png)

3. Unvanished (typed /vanish a second time):
![VV - Unvanished](https://user-images.githubusercontent.com/79672154/221373509-ff9fd57b-e69d-4b8b-80f8-d9673296946a.png)

The chat:
![VV - Unvanished Chat](https://user-images.githubusercontent.com/79672154/221373522-33af1a2b-be8e-4dd1-96e7-7c19bbfc4fdd.png)

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Please attach your configuration file

**Comment by DeOpping** [comment]
Config: https://paste.md-5.net/zasubajami.bash

**Comment by Syrent** [comment]
It works fine on my local server.
Just to confirm
- Did you install the plugin on both Velocity and Spigot?
- Does the plugin version is the same on Velocity and Spigot?
- Is this problem exists on all of your network servers?

**Comment by DeOpping** [comment]
Yes to all the questions

If it is only an issue for the network I'm working on, then that's fine, we most likely won't be using the auto vanish on join.

**Comment by Syrent** [comment]
I changed some parts of the code that may be fixed the problem on my local server. So, if it's be the problem it will be fixed in next plugin update.
