### ISSUE TITLE
Can't translate message and settings files

### ISSUE THREAD

**Issue by magef1x** [Syrent/VelocityVanish#147]
### Server backend version

Paper 1.19.4 Build 490

### Server Velocity version

Velocity 3.2.0 Build 247

### VelocityVanish version

3.18.1

### Describe the bug

I want to configurate the settings and language file but itsn't updating to new translated files. Can u add file structure like enchanced velocity? It will be easier for other developers and maybe it will be a solution to my problem.
![image](https://user-images.githubusercontent.com/114337601/229877313-af420cc6-a3d3-411b-93fa-72b4e9f5ddad.png)

### Expected behavior

These are the translated files

1) Language file https://cdn.discordapp.com/attachments/985981259127877702/1092870142708416583/en_US.yml

### Steps to reproduce

Step 1: Download the latest Velocity Vanish.
Step 2: Try to change settings.yml and en_US.yml of plugin.
Step 3: Save the changes.
Step 3: Restart your server.

### Checklist

- [X] I am running latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Everything works fine on my server
![Screenshot 2023-04-07 103323](https://user-images.githubusercontent.com/56670179/230559634-2240756c-69d1-4e83-96f1-63cd6a876367.png)

With your language config:
![image](https://user-images.githubusercontent.com/56670179/230559754-79c4c5bf-027b-4bda-b340-78786066a0a0.png)

**Comment by magef1x** [comment]
> Everything works fine on my server ![Screenshot 2023-04-07 103323](https://user-images.githubusercontent.com/56670179/230559634-2240756c-69d1-4e83-96f1-63cd6a876367.png)
> 
> With your language config: ![image](https://user-images.githubusercontent.com/56670179/230559754-79c4c5bf-027b-4bda-b340-78786066a0a0.png)

It's not working like that in my server. Is velocityvanish/velocityreport using client sided language system? Im using the english language in my client, that can be the reason of the problem.

**Comment by Syrent** [comment]
No, It's doesn't use client language at all

**Comment by magef1x** [comment]
![image](https://user-images.githubusercontent.com/114337601/230668854-f0880ac8-7d80-4e3c-8134-393066121848.png)
But you are using turkish language at client side on this screenshot

**Comment by Syrent** [comment]
It's VelocityVanish fake join/quit message

**Comment by magef1x** [comment]
Tested again but this issue still active. Can u change the file structure like enchanced velocity?

**Comment by Syrent** [comment]
It's already like EnhancedVelocity, the only difference is you must change settings and language on the spigot side. (I couldn't add it to the Velocity plugins folder because some servers need to change their settings per server based on their needs)

I'll try to investigate this problem more in the future but for now, I can't check it further with this much information, Everything work as expected on my server and my friend's server

Exact steps that I did to change language:
1. Install the plugin
2. Start the server
3. Change the language file on Spigot
4. Reload the plugin using the `/vanish reload` command
