### ISSUE TITLE
Using vanish command is broken on console

### ISSUE THREAD

**Issue by magef1x** [Syrent/VelocityVanish#148]
### Server backend version

Paper 1.19.4 Build 490

### Server Velocity version

Velocity 3.2.0 Build 247

### VelocityVanish version

3.18.1

### Describe the bug

Hi! I want to use vanish command on console but the plugin is conflicting with essentials and getting this error on console
![image](https://user-images.githubusercontent.com/114337601/229879906-52a16a83-ef9f-40d3-9327-a443e4204a8c.png)

### Expected behavior

Nothing changed on configuration of plugins

### Steps to reproduce

Step 1: Create a test server with essentials dev build and latest velocityvanish
Step 2: Try to use /vanish <playername> command on console

### Additional info

Full Server Log https://cdn.discordapp.com/attachments/985981259127877702/1092873327758024824/message.txt

### Checklist

- [X] I am running latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Try this version
[VelocityVanish v3.18.2.zip](https://github.com/Syrent/VelocityVanish/files/11161510/VelocityVanish.v3.18.2.zip)
Let me know if it solved your problem

**Comment by magef1x** [comment]
> Try this version [VelocityVanish v3.18.2.zip](https://github.com/Syrent/VelocityVanish/files/11161510/VelocityVanish.v3.18.2.zip) Let me know if it solved your problem

Fixed on this jar, thanks!

**Comment by Syrent** [comment]
Fixed
