### ISSUE TITLE
Suggestion: A toggle for join/leave messages

### ISSUE THREAD

**Issue by Callial** [Syrent/VelocityVanish#163]
If a server has more than like 30 active players at a time join and leave messages are extremely annoying. So we normally disable them. However, unless I am missing something, this plugin forces the message to exist which is honestly almost enough for me to not even bother with a vanish plugin since when a user vanishes it just says the user left, but when they leave we don't have a user left message. So players immediately know the player has vanished instead of actually leaving.

**Comment by Syrent** [comment]
You already can disable join/leave message, just leave them empty in you language file
Example:
```yml
vanish:
   ...
    join_message: ""
    quit_message: ""
```

**Comment by Callial** [comment]
Thanks, I still think it would be nice to add a toggle in the config, just so it is clear to users checking out your plugin that it is an option and not something they need to edit a language file for(Most people won't immediately assume to edit a language file to configure a plugin) But the feature does technically exist so I will close this here.
