### ISSUE TITLE
[Feature Request] DiscordSRV Joining/Leaving / Luckperms PAPI

### ISSUE THREAD

**Issue by ryzech** [Syrent/VelocityVanish#186]
Hello there! Most of the other vanish plugins I've used, and the one I'm coming from (SuperVanish), have support for discordsrv joining and leaving, but when i tested it here, it didn't seem to work, is there anyway you could try to get this working?
Here's the linked issue with the discordsrv methods - [issue](https://github.com/DiscordSRV/DiscordSRV/issues/220)

As well as that, it doesn't seem to support luckperms prefixes, as they use the legacy color codes, (i believe adventure api has a method for converting if that's what you're using, which i'd assume it is since it's the <color><color/> format) and when i use the PAPI replacement it inputs it out in literal text.

**Comment by Syrent** [comment]
Hi, You can add support for DiscordSRV using its internal event system (I'll try to implement them from code in future updates): https://github.com/Syrent/VelocityVanish/wiki/Compatibility#discordsrv-with-configuration
Also about legacy color codes, you can enable the `support_legacy_color_codes` option in `settings.yml`
