### ISSUE TITLE
velocityvanish.action.vanish.onjoin disables fly

### ISSUE THREAD

**Issue by Zoltus** [Syrent/VelocityVanish#205]
### Server backend version

1.20.1

### Server Velocity version

newest

### VelocityVanish version

3.18.2

### Describe the bug

If i set permission velocityvanish.action.vanish.onjoin to false, everytime admin or anyone joins it sets the fly disabled.

### Expected behavior

if im flying and rejoin server i should stay in fly mode still,

### Steps to reproduce

1. set permission velocityvanish.action.vanish.onjoin false
2. put gm 1 and fly,
3. rejoin server and you will fall

### Checklist

- [X] I am running latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Try last beta build

**Comment by Zoltus** [comment]
> Try last beta build

Fixed
