### ISSUE TITLE
EssentialsX Hook error

### ISSUE THREAD

**Issue by redgabri** [Syrent/VelocityVanish#218]
### Server backend version

Paper 1.20

### Server backend Java version

OpenJDK 17

### Server Velocity version

Velocity 3.2.0

### Server Velocity Java version

OpenJDK 17

### VelocityVanish version

latest

### Describe the bug

When you vanish yourself (im using the plugin command 100% because i tried "velocityvanish:vanish") you get invisibility instead of vanishing... i know for a fact that essentials is causing the problem so please fix or add an option to the config

### Expected behavior

Vanish you instead of givving invisibility

### Steps to reproduce

1) Install essentialsX and velocityvanish
2) Type /sayanvanish (or any command to vanish using velocityvanish)

### LuckPerms webview link

i'm using an opped account

### VelocityVanish's configuration file

im using an opped account

### Plugins

I know it's essentials causing the problem because i read the src and essentials give invisibility while vanished

### Checklist

- [X] I am running the latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I tried the plugin on a fresh server and it didn't work (Or it worked but I know exactly which plugin it's incompatible with)
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
You should acquire both 'invisibility' and 'vanish'. However, I'm unable to assist you with the current issue's content. Let's address a few points:

1. `latest` is not a specific version.
2. `1.20` is not supported. It seems you meant `1.20.1`, but complete information is crucial.
3. I require the results from `/plugins` to be provided under the **Plugins** section.
4. Please include the complete latest log of your server in the **Additional Info** section.

**Comment by Syrent** [comment]
this issue was inactive for a long time, i'll close it for now. if the problem still persist in latest VelocityVanish version, please reopen this issue.
