### ISSUE TITLE
Able to fly after unvanished

### ISSUE THREAD

**Issue by GronyRalph** [Syrent/VelocityVanish#248]
### Server backend version

1.8.8

### Server backend Java version

17

### Server Velocity version

3.2.0-SNAPSHOT (git-19abb909-b265)

### Server Velocity Java version

17

### VelocityVanish version

3.26.0-build.18

### Describe the bug

I set up the permission to fly when vanished but I can still fly after unvanished which is not expected

### Expected behavior

To reset flying ability, disable it
Of course not if you're on creative but you can fly in survival and adventure mode currently

### Steps to reproduce

Vanish, then unvanish

### LuckPerms webview link

https://luckperms.net/editor/pNIux9ZeGZ

### VelocityVanish's configuration file

# Full wiki is available at https://github.com/Syrent/VelocityVanish/wiki
config_version: 7
default_language: en_US
show_dependency_suggestions: true
support_legacy_color_codes: false
force_vanish_if_first: true
bstats: true
sounds:
  command: ENTITY_EXPERIENCE_ORB_PICKUP
  vanish: ENTITY_EXPERIENCE_ORB_PICKUP
  unvanish: ENTITY_EXPERIENCE_ORB_PICKUP
vanish:
  actionbar: true
  remember: true
  see_as_spectator: true
  invincible: true
  fake_join_leave_message: true
  silent_open_container: true
  prevent:
    pickup: true
    block_break: false
    block_place: false
    interact: false
    advancement: true
hooks:
  essentials:
    force_prevent_private_messages: false

### Plugins

VelocityVanish

### Checklist

- [X] I am running the latest version of the plugin on both Velocity and Spigot
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I tried the plugin on a fresh server and it didn't work (Or it worked but I know exactly which plugin it's incompatible with)
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
The most recent snapshot now features an updated fly control system
