### ISSUE TITLE
%velocityvanish_vanished%

### ISSUE THREAD

**Issue by i777555** [Syrent/VelocityVanish#266]
![image](https://github.com/Syrent/VelocityVanish/assets/148570793/41ed74e8-ebdc-483c-82c1-0f67456c2663)
can you do %velocityvanish_vanished% messages customizable

**Comment by Syrent** [comment]
I'll add the option to change the values in next update

**Comment by i777555** [comment]
and can you add joined vanished and left vanished messages for staff

**Comment by Syrent** [comment]
on a second thought i guess it's better to use TAB itself to replace placeholder results. TAB has a feature to replace placeholders: https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements
making placeholder results customizable isn't something that i like to do
