### ISSUE TITLE
Task #27 for SayanVanish v1.0.0-rc.9-SNAPSHOT-413244f generated an exception

### ISSUE THREAD

**Issue by modpotato** [Syrent/VelocityVanish#312]
completely stock installation with a velocity server (proxy protocol, modern fwding) and a 1.20.6 server behind it.
full error:
https://logpaste.com/SwhOEsOe

**Comment by EmanYm** [comment]
Every single hour with incremented task numbers
https://hastebin.com/share/cibacayuni.ruby

currently only installed on one back-end server on my network for testing purposes
- Purpur 1.20.6 build 2227 [79d199c]
- SayanVanish 1.0 RC9 [413244f]
update-checker is set to false in the config
Not set up on a database at this time

**Comment by Syrent** [comment]
try release 1.0.0
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.0.0

**Comment by EmanYm** [comment]
That release loaded without issue.  I will monitor the console to see if it throws any exceptions.
Thank you, Syrent.

**Comment by Syrent** [comment]
what about just `/sayanvanish`

**Comment by Syrent** [comment]
send an screenshot from `/ver SayanVanish` and `/paper version`

**Comment by Syrent** [comment]
there is good chance that older builds of paper 1.20.6 don't work. paper recently changed the command system to a better one and i adopted those changes in SayanVanish
