### ISSUE TITLE
The sound is played after shulkerbox is closed

### ISSUE THREAD

**Issue by cmx-root** [Syrent/VelocityVanish#341]
The sound is played after shulkerbox is closed. `silent_container` feature is enabled.

Plugin Version: `1.5.0-b192` from Modrinth.
Minecraft Version: `1.21.1` Paper build 118.

**Comment by Syrent** [comment]
try this build:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.5.0-SNAPSHOT-build.195
