### ISSUE TITLE
[Bungee] Kick when trying to tab complete

### ISSUE THREAD

**Issue by cmx-root** [Syrent/VelocityVanish#345]
```
[INFO]: [player] disconnected with: Error : Method became inaccessible: TabCompleteEvent(super=TargetedEvent(sender=player, receiver=net.md_5.bungee.ServerConnection@4bd6afe0), cancelled=false, cursor=/login , suggestions=[]) @ net.md_5.bungee.event.EventBus:46
```

**Comment by Syrent** [comment]
> Maybe this shouldn't be private. But I can't build SayanVanish. There's `-sources` and `-unshaded` jars in `/sayanvanish-proxy/sayanvanish-bungeecord/build/libs/` folder, both don't work

The main plugin JAR files will be generated in the `bin` directory located within the project root directory:
![image](https://github.com/user-attachments/assets/475a7f26-de80-4228-93ef-996416a7a3c5)

**Comment by Syrent** [comment]
try this build:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.5.0-SNAPSHOT-build.196
