### ISSUE TITLE
1.19.3 Packet Missing

### ISSUE THREAD

**Issue by RockinChaos** [Syrent/VelocityVanish#65]
### Server backend version

1.19.3 - PaperSpigot

### Server Velocity version

N/A

### VelocityVanish version

3.10.1

### Describe the bug

Getting this error on PaperSpigot 1.19.3 using the latest December 7th dev build of ProtocolLib.
Pastebin error; https://pastebin.com/r98HD7Gb

Everything else works but this error is spammed when entering vanish.

### Expected behavior

No error to appear

### Steps to reproduce

Default install, drag/drop the release jar and start the server.
Once you enter vanish mode the error occurs.

### Additional info

N/A

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Use the December 14th dev build of ProtocolLib.
Download link: https://ci.dmulloy2.net/job/ProtocolLib/607/

Let me know if it's solved the problem.

**Comment by RockinChaos** [comment]
Dang that timing, looks like they pushed an update right as I posted my issue haha.

Well, good news the original issue disappeared, however, I am now getting a different error, the same behavior just a different stacktrace.

Error; https://pastebin.com/q78b1QKz

- Using the b607 of ProtocolLib
- Using the latest compile of PaperSpigot -> b328 for 1.19.3

**Comment by Syrent** [comment]
I think it's a ProtoclLib bug.
Anyway, can you send me the `/protocol dump` result?

**Comment by RockinChaos** [comment]
Here is the attached Protocol dump;
[dump-2022-12-14_16.41.16.txt](https://github.com/Syrent/VelocityVanish/files/10232753/dump-2022-12-14_16.41.16.txt)

**Comment by Syrent** [comment]
I created an issue for this bug on ProtocolLib (https://github.com/dmulloy2/ProtocolLib/issues/2041).

**Comment by Syrent** [comment]
Hi, Try this version:
https://github.com/Syrent/VelocityVanish/releases/tag/v3.10.2-beta.1

**Comment by RockinChaos** [comment]
Unfortunately upon vanish and unvanish this error is occurring, it seems different from before.
Error; https://pastebin.com/WMxNebZp

**Comment by Syrent** [comment]
Mojang changed the `Player Info` behavior completely on `1.19.3`.
For now, I just ignored that part.
New version: https://github.com/Syrent/VelocityVanish/releases/tag/v3.10.2-beta.2

**Comment by Syrent** [comment]
TODO: Use RUoM for packet handling and remove ProtocolLib

**Comment by Syrent** [comment]
Waiting for 1.19.4/1.20 release...

**Comment by Syrent** [comment]
> **TODO:** Use RUoM for packet handling and remove ProtocolLib

I'll implement the NMS/Packet part without using RUoM or ProtocolLib
