### ISSUE TITLE
Could not pass event TabCompleteEvent to VelocityVanish v3.10.2

### ISSUE THREAD

**Issue by YKDZ** [Syrent/VelocityVanish#71]
### Server backend version

Purpur 1.19.2

### Server Velocity version

Velocity-3.1.2-SNAPSHOT-201

### VelocityVanish version

3.10.2

### Describe the bug

https://mcpaste.com/6011215ea758efee774313613fc6507a

### Expected behavior

Nothing

### Steps to reproduce

Nothing

### Additional info

Nothing

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
I'll fix the problem in the next update.

**Comment by Syrent** [comment]
Try this version:
https://cdn.discordapp.com/attachments/1036292004650418216/1058543853025632386/VelocityVanish_v3.10.2.jar

Let me know if it worked.

**Comment by Syrent** [comment]
Fixed in 3.11.1
